### ISSUE TITLE
Haybot

### ISSUE THREAD

**Issue by samuelhamersky** [NicePotato-MS/HayBot#1]
Hello i have a few questions about ur code.

Is this still usable for the current hay day?
How to i run this on my computer? (downloading the files etc...step for step pls)
From where do i need to download hay day on my computer for this work?

Would rly appreicate it. 
if you do cant provide help i would ask if you know what i can do if  i want to have a farm bot on my computer without any android emulators because i only have iphone/ios

**Comment by NicePotato-MS** [comment]
Read the updated README
